export default {
    SET_POKEMON_TABLE_ITEMS: 'SET_POKEMON_TABLE_ITEMS',
    SET_POKEMON_TABLE_PAGE_NUMBER: 'SET_POKEMON_TABLE_PAGE_NUMBER',
    SET_POKEMON_TABLE_PAGE_SIZE: 'SET_POKEMON_TABLE_PAGE_SIZE',
    SET_SELECTED_POKEMON: 'SET_SELECTED_POKEMON',
    SET_POKEMON_TABLE_LOADING_ON: 'SET_POKEMON_TABLE_LOADING_ON',
    SET_POKEMON_TABLE_LOADING_OFF: 'SET_POKEMON_TABLE_LOADING_OFF',

    HIDE_ERROR_DIALOG: 'HIDE_ERROR_DIALOG',
    SET_ERROR_DIALOG: 'SET_ERROR_DIALOG',
    SHOW_ERROR_DIALOG: 'SHOW_ERROR_DIALOG'
};
